### H2データベース接続設定
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:~/.h2/taskdb
spring.datasource.username=gihyo
spring.datasource.password=gihyodb

### H2コンソールを有効化。以下のURLにブラウザからアクセスする
### http://localhost:8080/h2-console
spring.h2.console.enabled=true

### データベース初期化用DDL実行モード
spring.sql.init.mode=always
spring.sql.init.encoding=utf-8
